slug: disecad
visit: visit
charts:
- chart: sex
  title: sex
- chart: race
  title: race
  
webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org